# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff9dc930d3b5fd04faa41ad96949b9e51341506518be3964aec9e8d89959d50db62d27dcb53b124ad9d345ac61aaffb0967e25fd9659803d5a719468b05cf1f7

test:
  secret_key_base: e65a83c17107ffe2abbe16154c754e8e39193263c6f95bb705491ff261ccaecd91cb8181db156aa548357d101297a1eaac84a213b21548d1c1319b83ad786003

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
